lane :test do
  redmine_file_upload(
    redmine_host: 'https://www.ruby.org',
    redmine_api_key: 'api-key',
    redmine_use_ssl: 'true',
    file_path: "path/to/file"
  )
  redmine_file_post(
    redmine_host: 'https://www.ruby.org',
    redmine_api_key: 'api-key',
    redmine_use_ssl: 'true',
    redmine_project: 'project_id',
    file_name: lane_context[SharedValues:: REDMINE_UPLOAD_FILE_NAME],
    file_token: lane_context[SharedValues::REDMINE_UPLOAD_FILE_TOKEN],
    file_version: "",
    file_description: "This is a file"
  )
end
